import { Product, Category, BlogPost } from './types';

export const HERO_IMAGE = 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1600&auto=format&fit=crop';
export const SUMMER_MODEL_IMAGE = 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1000&auto=format&fit=crop';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-necklaces',
    name: 'NECKLACES',
    subtext: 'DISCOVER COLLECTION',
    linkCategory: 'Necklaces',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'cat-earrings',
    name: 'EARRINGS',
    subtext: 'DISCOVER COLLECTION',
    linkCategory: 'Earrings',
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=800&auto=format&fit=crop',
  },
  {
    id: 'cat-rings',
    name: 'RINGS',
    subtext: 'DISCOVER COLLECTION',
    linkCategory: 'Rings',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Radiant Circle Pendant',
    category: 'Necklaces',
    price: 9999,
    originalPrice: 11999,
    rating: 4.9,
    reviewsCount: 142,
    sku: 'GLW-NK-001',
    material: '18k Rose Gold Vermeil',
    stoneDetails: 'AAA Pink Sapphire & Cubic Zirconia',
    deliveryEstimate: '2-3 Business Days (Express Available)',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'A signature fine necklace in 18k Rose Gold Vermeil featuring a halo circle pendant embedded with hand-set micro-pavé pink sapphire crystals.',
    isBestseller: true,
    isSummerCollection: true,
    isSale: true,
    inStock: true,
    variants: ['18k Rose Gold', '18k Yellow Gold', '925 Sterling Silver'],
    details: [
      'Base: 925 Sterling Silver dipped in 2.5 microns 18k Rose Gold',
      'Pendant Diameter: 14mm pavé circle',
      'Chain Length: 16" + 2" extension',
      'Anti-tarnish luxury coating & 100% Nickel-Free',
    ],
    materialsCare: 'Avoid direct application of perfumes or harsh lotions. Clean with a soft microfiber jewelry cloth after wear.',
    shippingReturns: 'Complimentary shipping over ₹2,999. Hassle-free 30-day returns in original GLOW & CO. velvet packaging.',
  },
  {
    id: 'prod-2',
    name: 'Blush Luxe Huggie Hoops',
    category: 'Earrings',
    price: 7499,
    rating: 4.8,
    reviewsCount: 98,
    sku: 'GLW-ER-002',
    material: '18k Rose Gold Plated Brass',
    stoneDetails: 'Blush Pink Swarovski Crystals',
    deliveryEstimate: '1-2 Business Days',
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'Featherlight huggie hoop earrings featuring channel-set blush rose crystals that bring a delicate feminine radiance to any look.',
    isBestseller: true,
    isSummerCollection: true,
    inStock: true,
    variants: ['Rose Gold Finish', 'Sterling Silver Finish'],
    details: [
      'Outer Diameter: 15mm | Width: 2.5mm',
      'Secure click-latch closure for day-to-night comfort',
      'Sweat & Water Resistant Finish',
    ],
    materialsCare: 'Store in dry velvet box away from direct heat.',
    shippingReturns: 'Free 30-day returns & exchanges on all earring orders.',
  },
  {
    id: 'prod-3',
    name: 'Rose Halo Diamond Solitaire',
    category: 'Rings',
    price: 11499,
    originalPrice: 13999,
    rating: 4.9,
    reviewsCount: 215,
    sku: 'GLW-RG-003',
    material: 'Solid 18k Rose Gold Vermeil',
    stoneDetails: '1.25 ct Brilliant Cut Pink Diamond Simulant',
    deliveryEstimate: '2-4 Business Days',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'An ethereal halo solitaire ring featuring a 1.25 ct equivalent round-cut pink stone surrounded by a pavé halo and micro-band.',
    isBestseller: true,
    isSale: true,
    inStock: true,
    variants: ['18k Rose Gold', 'Gold Vermeil', '925 Sterling Silver'],
    sizes: ['US 5', 'US 6', 'US 7', 'US 8', 'US 9'],
    details: [
      'Material: 18k Rose Gold over 925 Sterling Silver',
      'Center Stone: 1.25 ct AAA grade pink diamond simulant',
      'Band Width: Ultra-sleek 1.5mm comfort band',
    ],
    materialsCare: 'Clean gently using warm water and mild soap.',
    shippingReturns: 'Includes Ring Size Guarantee with 100% free size exchanges.',
  },
  {
    id: 'prod-4',
    name: 'Silk Paperclip Chain Bracelet',
    category: 'Bracelets',
    price: 6999,
    rating: 4.8,
    reviewsCount: 86,
    sku: 'GLW-BR-004',
    material: '18k Rose Gold Vermeil',
    stoneDetails: 'Mini Rose Quartz Charm',
    deliveryEstimate: '2-3 Business Days',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'A delicate paperclip style chain bracelet crafted in 18k Rose Gold Vermeil with a dangling mini rose quartz droplet charm.',
    isBestseller: true,
    isSummerCollection: true,
    inStock: true,
    variants: ['18k Rose Gold', 'Sterling Silver'],
    sizes: ['Small (6.5")', 'Medium (7.0")', 'Large (7.5")'],
    details: [
      'Link Dimensions: 3mm x 7mm paperclip links',
      '1.5" extender chain with custom logo charm',
      'Engraved GLOW lobster clasp',
    ],
    materialsCare: 'Resistant to daily wear. Wipe dry after swimming or workouts.',
    shippingReturns: 'Complimentary shipping & 30-day return policy.',
  },
  {
    id: 'prod-5',
    name: 'Petal Sunburst Medallion',
    category: 'Necklaces',
    price: 8999,
    rating: 4.9,
    reviewsCount: 64,
    sku: 'GLW-NK-005',
    material: '18k Rose Gold Plated Silver',
    stoneDetails: 'Center Crystal Accent',
    deliveryEstimate: '2-3 Business Days',
    image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'Radiant petal-inspired sunburst coin pendant offering golden warmth and romantic feminine allure.',
    isSummerCollection: true,
    isNew: true,
    inStock: true,
    variants: ['Rose Gold', 'Yellow Gold'],
    details: [
      'Diameter: 18mm Medallion',
      'Chain: 18" beaded saturn chain',
      'High-gloss mirror polish',
    ],
    materialsCare: 'Polish dry with plush velvet polishing cloth.',
    shippingReturns: 'Includes gift box and satin pouch.',
  },
  {
    id: 'prod-6',
    name: 'Twisted Rose Huggie Hoops',
    category: 'Earrings',
    price: 6499,
    rating: 4.7,
    reviewsCount: 42,
    sku: 'GLW-ER-006',
    material: '18k Rose Gold Vermeil',
    stoneDetails: 'High-Polish Textured Gold',
    deliveryEstimate: '1-3 Business Days',
    image: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'Textured rope-twist hoop earrings creating elegant dimensional rose reflections around your face.',
    isNew: true,
    inStock: true,
    variants: ['Rose Gold', 'Sterling Silver'],
    details: [
      'Diameter: 13mm hugging profile',
      'Designed for sleep and active wear',
    ],
    materialsCare: 'Wipe with microfiber cloth after use.',
    shippingReturns: '30-day money-back guarantee.',
  },
  {
    id: 'prod-7',
    name: 'Celestial Pink Starburst Ring',
    category: 'Rings',
    price: 9499,
    rating: 4.9,
    reviewsCount: 77,
    sku: 'GLW-RG-007',
    material: '18k Rose Gold Vermeil',
    stoneDetails: 'Hand-Engraved Pink Sapphire Accents',
    deliveryEstimate: '2-4 Business Days',
    image: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'Inspired by starlight, this domed ring features hand-engraved starburst motifs inset with glistening rose crystals.',
    isNew: true,
    inStock: true,
    variants: ['Rose Gold', 'Silver'],
    sizes: ['US 6', 'US 7', 'US 8'],
    details: [
      'Band Width: 3.5mm dome profile',
      'Solid 925 Sterling Silver inner core',
    ],
    materialsCare: 'Keep stored in protective pouch.',
    shippingReturns: 'Free returns & size exchanges.',
  },
  {
    id: 'prod-8',
    name: 'Rose Crystal Tennis Bracelet',
    category: 'Bracelets',
    price: 12999,
    originalPrice: 14999,
    rating: 5.0,
    reviewsCount: 110,
    sku: 'GLW-BR-008',
    material: '925 Sterling Silver with Rose Gold Plating',
    stoneDetails: '3mm Round Pink Cubic Zirconia',
    deliveryEstimate: '1-2 Business Days',
    image: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop',
    ],
    description: 'A luxurious continuous strand of claw-set pink crystals designed to add red-carpet glamour to any attire.',
    isBestseller: true,
    isSale: true,
    inStock: true,
    variants: ['Rose Gold', 'White Gold'],
    sizes: ['6.5 Inches', '7.0 Inches'],
    details: [
      '4-Prong Basket Setting',
      'Double Safety Latch Clasp',
    ],
    materialsCare: 'Avoid contact with harsh chemicals.',
    shippingReturns: 'Complimentary 2-day express shipping.',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'post-1',
    title: 'The Art of Styling Rose Gold & Pink Gems',
    subtitle: 'Master the subtle rules of warm tones, delicate layering, and romantic accents.',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop',
    date: 'June 18, 2026',
    readTime: '4 min read',
    author: 'Elena Vance, Senior Stylist',
    content: `Rose gold creates a soft, romantic glow against any skin tone. To layer rose gold effortlessly:

1. Pair Warm Metals with Blush Stones: Combine 18k Rose Gold Vermeil chains with rose quartz or pink sapphire pendants.
2. Layer Different Textures: Mix paperclip chains with delicate pavé hoops for depth.
3. Keep it Soft: Let your jewelry complement your natural radiance rather than overpowering it.`,
  },
  {
    id: 'post-2',
    title: 'Summer High Jewelry Trends 2026',
    subtitle: 'From soft pink tones to oceanic pearls and vibrant stackable rings.',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
    date: 'July 02, 2026',
    readTime: '5 min read',
    author: 'Sophia Chen, Creative Director',
    content: `This season embraces feminine grace and luminous warmth. Key trends include:

- Organic Soft Shapes: Curves, petals, and starburst medallions.
- Rose Gold Stacks: Layering multiple rings across fingers for a playful yet refined look.
- Tarnish-Proof Luxury Coatings: High-micron vermeil finishes built for everyday glamour.`,
  },
  {
    id: 'post-3',
    title: 'Caring For Your Rose Gold Vermeil Pieces',
    subtitle: 'Keep your fine jewelry shining like new for decades.',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop',
    date: 'July 14, 2026',
    readTime: '3 min read',
    author: 'Marcus Vance, Master Craftsman',
    content: `Gold Vermeil features a thick 2.5-micron layer of 18k gold electroplated over sterling silver.

- Put Jewelry On Last: Apply lotions and perfumes first.
- Dry Storage: Keep pieces in sealed velvet pouches.
- Gentle Polishing: Wipe with a soft microfiber polishing cloth.`,
  },
];

export const INSTAGRAM_PHOTOS = [
  {
    id: 'ig-1',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
    alt: 'Model wearing Rose Gold Glow Necklace',
    likes: '2.8k',
    handle: '@elena_vance',
  },
  {
    id: 'ig-2',
    url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=600&auto=format&fit=crop',
    alt: 'Luxury Rose Gold Jewelry Styling',
    likes: '3.4k',
    handle: '@glowandco',
  },
  {
    id: 'ig-3',
    url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600&auto=format&fit=crop',
    alt: 'Rose Gold Stack Styling',
    likes: '1.9k',
    handle: '@sophia_style',
  },
];
